// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for ApiErrorClass.
const (
	ApiErrorClassOperatorActionRequired ApiErrorClass = "operator_action_required"
	ApiErrorClassPermission             ApiErrorClass = "permission"
	ApiErrorClassTransient              ApiErrorClass = "transient"
	ApiErrorClassValidation             ApiErrorClass = "validation"
)

// Valid indicates whether the value is a known member of the ApiErrorClass enum.
func (e ApiErrorClass) Valid() bool {
	switch e {
	case ApiErrorClassOperatorActionRequired:
		return true
	case ApiErrorClassPermission:
		return true
	case ApiErrorClassTransient:
		return true
	case ApiErrorClassValidation:
		return true
	default:
		return false
	}
}

// Defines values for GCStatusResponseStatus.
const (
	GCStatusResponseStatusDone    GCStatusResponseStatus = "done"
	GCStatusResponseStatusFailed  GCStatusResponseStatus = "failed"
	GCStatusResponseStatusIdle    GCStatusResponseStatus = "idle"
	GCStatusResponseStatusRunning GCStatusResponseStatus = "running"
)

// Valid indicates whether the value is a known member of the GCStatusResponseStatus enum.
func (e GCStatusResponseStatus) Valid() bool {
	switch e {
	case GCStatusResponseStatusDone:
		return true
	case GCStatusResponseStatusFailed:
		return true
	case GCStatusResponseStatusIdle:
		return true
	case GCStatusResponseStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for GitRefType.
const (
	Branch GitRefType = "branch"
	Tag    GitRefType = "tag"
)

// Valid indicates whether the value is a known member of the GitRefType enum.
func (e GitRefType) Valid() bool {
	switch e {
	case Branch:
		return true
	case Tag:
		return true
	default:
		return false
	}
}

// Defines values for GitTreeEntryType.
const (
	Blob   GitTreeEntryType = "blob"
	Commit GitTreeEntryType = "commit"
	Tree   GitTreeEntryType = "tree"
)

// Valid indicates whether the value is a known member of the GitTreeEntryType enum.
func (e GitTreeEntryType) Valid() bool {
	switch e {
	case Blob:
		return true
	case Commit:
		return true
	case Tree:
		return true
	default:
		return false
	}
}

// Defines values for RepoBlockOnSeverity.
const (
	RepoBlockOnSeverityCritical RepoBlockOnSeverity = "critical"
	RepoBlockOnSeverityHigh     RepoBlockOnSeverity = "high"
	RepoBlockOnSeverityLow      RepoBlockOnSeverity = "low"
	RepoBlockOnSeverityMedium   RepoBlockOnSeverity = "medium"
	RepoBlockOnSeverityNone     RepoBlockOnSeverity = "none"
)

// Valid indicates whether the value is a known member of the RepoBlockOnSeverity enum.
func (e RepoBlockOnSeverity) Valid() bool {
	switch e {
	case RepoBlockOnSeverityCritical:
		return true
	case RepoBlockOnSeverityHigh:
		return true
	case RepoBlockOnSeverityLow:
		return true
	case RepoBlockOnSeverityMedium:
		return true
	case RepoBlockOnSeverityNone:
		return true
	default:
		return false
	}
}

// Defines values for RepoCreateBlockOnSeverity.
const (
	RepoCreateBlockOnSeverityCritical RepoCreateBlockOnSeverity = "critical"
	RepoCreateBlockOnSeverityHigh     RepoCreateBlockOnSeverity = "high"
	RepoCreateBlockOnSeverityLow      RepoCreateBlockOnSeverity = "low"
	RepoCreateBlockOnSeverityMedium   RepoCreateBlockOnSeverity = "medium"
	RepoCreateBlockOnSeverityNone     RepoCreateBlockOnSeverity = "none"
)

// Valid indicates whether the value is a known member of the RepoCreateBlockOnSeverity enum.
func (e RepoCreateBlockOnSeverity) Valid() bool {
	switch e {
	case RepoCreateBlockOnSeverityCritical:
		return true
	case RepoCreateBlockOnSeverityHigh:
		return true
	case RepoCreateBlockOnSeverityLow:
		return true
	case RepoCreateBlockOnSeverityMedium:
		return true
	case RepoCreateBlockOnSeverityNone:
		return true
	default:
		return false
	}
}

// Defines values for RepoPatchBlockOnSeverity.
const (
	Critical RepoPatchBlockOnSeverity = "critical"
	High     RepoPatchBlockOnSeverity = "high"
	Low      RepoPatchBlockOnSeverity = "low"
	Medium   RepoPatchBlockOnSeverity = "medium"
	None     RepoPatchBlockOnSeverity = "none"
)

// Valid indicates whether the value is a known member of the RepoPatchBlockOnSeverity enum.
func (e RepoPatchBlockOnSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for ScanStatus.
const (
	ScanStatusDone    ScanStatus = "done"
	ScanStatusFailed  ScanStatus = "failed"
	ScanStatusPending ScanStatus = "pending"
	ScanStatusRunning ScanStatus = "running"
)

// Valid indicates whether the value is a known member of the ScanStatus enum.
func (e ScanStatus) Valid() bool {
	switch e {
	case ScanStatusDone:
		return true
	case ScanStatusFailed:
		return true
	case ScanStatusPending:
		return true
	case ScanStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for SearchResultKind.
const (
	SearchResultKindArtifact SearchResultKind = "artifact"
	SearchResultKindCve      SearchResultKind = "cve"
	SearchResultKindDeb      SearchResultKind = "deb"
	SearchResultKindHelm     SearchResultKind = "helm"
	SearchResultKindPypi     SearchResultKind = "pypi"
	SearchResultKindRepo     SearchResultKind = "repo"
	SearchResultKindRpm      SearchResultKind = "rpm"
)

// Valid indicates whether the value is a known member of the SearchResultKind enum.
func (e SearchResultKind) Valid() bool {
	switch e {
	case SearchResultKindArtifact:
		return true
	case SearchResultKindCve:
		return true
	case SearchResultKindDeb:
		return true
	case SearchResultKindHelm:
		return true
	case SearchResultKindPypi:
		return true
	case SearchResultKindRepo:
		return true
	case SearchResultKindRpm:
		return true
	default:
		return false
	}
}

// Defines values for SyncJobStatus.
const (
	Done    SyncJobStatus = "done"
	Failed  SyncJobStatus = "failed"
	Pending SyncJobStatus = "pending"
	Running SyncJobStatus = "running"
)

// Valid indicates whether the value is a known member of the SyncJobStatus enum.
func (e SyncJobStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for TLSCertInfoSource.
const (
	TLSCertInfoSourceSelfSigned TLSCertInfoSource = "self-signed"
	TLSCertInfoSourceUploaded   TLSCertInfoSource = "uploaded"
)

// Valid indicates whether the value is a known member of the TLSCertInfoSource enum.
func (e TLSCertInfoSource) Valid() bool {
	switch e {
	case TLSCertInfoSourceSelfSigned:
		return true
	case TLSCertInfoSourceUploaded:
		return true
	default:
		return false
	}
}

// Defines values for TrivyDBStatusSource.
const (
	TrivyDBStatusSourceBakedIn      TrivyDBStatusSource = "baked-in"
	TrivyDBStatusSourceOnlinePulled TrivyDBStatusSource = "online-pulled"
	TrivyDBStatusSourceUploaded     TrivyDBStatusSource = "uploaded"
)

// Valid indicates whether the value is a known member of the TrivyDBStatusSource enum.
func (e TrivyDBStatusSource) Valid() bool {
	switch e {
	case TrivyDBStatusSourceBakedIn:
		return true
	case TrivyDBStatusSourceOnlinePulled:
		return true
	case TrivyDBStatusSourceUploaded:
		return true
	default:
		return false
	}
}

// Defines values for VulnerabilitySeverity.
const (
	CRITICAL VulnerabilitySeverity = "CRITICAL"
	HIGH     VulnerabilitySeverity = "HIGH"
	LOW      VulnerabilitySeverity = "LOW"
	MEDIUM   VulnerabilitySeverity = "MEDIUM"
	UNKNOWN  VulnerabilitySeverity = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the VulnerabilitySeverity enum.
func (e VulnerabilitySeverity) Valid() bool {
	switch e {
	case CRITICAL:
		return true
	case HIGH:
		return true
	case LOW:
		return true
	case MEDIUM:
		return true
	case UNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for SearchParamsKind.
const (
	SearchParamsKindArtifact SearchParamsKind = "artifact"
	SearchParamsKindCve      SearchParamsKind = "cve"
	SearchParamsKindDeb      SearchParamsKind = "deb"
	SearchParamsKindHelm     SearchParamsKind = "helm"
	SearchParamsKindPypi     SearchParamsKind = "pypi"
	SearchParamsKindRepo     SearchParamsKind = "repo"
	SearchParamsKindRpm      SearchParamsKind = "rpm"
)

// Valid indicates whether the value is a known member of the SearchParamsKind enum.
func (e SearchParamsKind) Valid() bool {
	switch e {
	case SearchParamsKindArtifact:
		return true
	case SearchParamsKindCve:
		return true
	case SearchParamsKindDeb:
		return true
	case SearchParamsKindHelm:
		return true
	case SearchParamsKindPypi:
		return true
	case SearchParamsKindRepo:
		return true
	case SearchParamsKindRpm:
		return true
	default:
		return false
	}
}

// APIKey defines model for APIKey.
type APIKey struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Id         *int64     `json:"id,omitempty"`
	Label      *string    `json:"label,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Prefix     *string    `json:"prefix,omitempty"`
}

// APIKeyCreate defines model for APIKeyCreate.
type APIKeyCreate struct {
	Label string `json:"label"`
}

// APIKeyCreateResponse defines model for APIKeyCreateResponse.
type APIKeyCreateResponse struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Label     *string    `json:"label,omitempty"`
	Prefix    *string    `json:"prefix,omitempty"`

	// Secret Shown once at creation time only
	Secret *string `json:"secret,omitempty"`
}

// ActivityEvent defines model for ActivityEvent.
type ActivityEvent struct {
	Action     *string                 `json:"action,omitempty"`
	Actor      *string                 `json:"actor,omitempty"`
	Details    *map[string]interface{} `json:"details,omitempty"`
	Id         *int64                  `json:"id,omitempty"`
	TargetId   *string                 `json:"target_id,omitempty"`
	TargetKind *string                 `json:"target_kind,omitempty"`
	Timestamp  *time.Time              `json:"timestamp,omitempty"`
}

// ActivityListResponse defines model for ActivityListResponse.
type ActivityListResponse struct {
	Items      *[]ActivityEvent `json:"items,omitempty"`
	NextCursor *string          `json:"next_cursor,omitempty"`
}

// ApiErrorClass Stable client-facing error classification — drives UI icon/copy/CTA.
type ApiErrorClass string

// ApiErrorEnvelope defines model for ApiErrorEnvelope.
type ApiErrorEnvelope struct {
	// Class Stable client-facing error classification — drives UI icon/copy/CTA.
	Class ApiErrorClass `json:"class"`

	// Code Stable machine identifier (e.g. "repo.not_found")
	Code    string                    `json:"code"`
	Details *ApiErrorEnvelope_Details `json:"details,omitempty"`

	// Hint Optional single-sentence remediation guidance
	Hint *string `json:"hint,omitempty"`

	// IncidentId Server-generated correlation ID (UUID v7) — matches slog request_id and the X-Incident-Id response header
	IncidentId *string `json:"incident_id,omitempty"`

	// Message Human-friendly single-sentence message (no internal paths)
	Message string `json:"message"`
}

// ApiErrorEnvelope_Details defines model for ApiErrorEnvelope.Details.
type ApiErrorEnvelope_Details struct {
	// Field Dot-path of the offending form field (validation class)
	Field *string `json:"field,omitempty"`

	// Fields Map of field-path to error-code for multi-field validation failures
	Fields *map[string]string `json:"fields,omitempty"`

	// OperatorLabel CTA label for the operator deep-link (e.g. "Go to Admin → Trivy")
	OperatorLabel *string `json:"operator_label,omitempty"`

	// OperatorRoute UI path (e.g. "/admin/trivy") for operator_action_required deep-link
	OperatorRoute *string `json:"operator_route,omitempty"`

	// RetryAfterMs Suggested retry delay in ms (transient class)
	RetryAfterMs         *int                   `json:"retry_after_ms,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action     *string                 `json:"action,omitempty"`
	Actor      *string                 `json:"actor,omitempty"`
	Details    *map[string]interface{} `json:"details,omitempty"`
	Id         *int64                  `json:"id,omitempty"`
	Ip         *string                 `json:"ip,omitempty"`
	Outcome    *string                 `json:"outcome,omitempty"`
	TargetId   *string                 `json:"target_id,omitempty"`
	TargetKind *string                 `json:"target_kind,omitempty"`
	Timestamp  *time.Time              `json:"timestamp,omitempty"`
	UserAgent  *string                 `json:"user_agent,omitempty"`
}

// AuditListResponse defines model for AuditListResponse.
type AuditListResponse struct {
	Items      *[]AuditEvent `json:"items,omitempty"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	Current string `json:"current"`
	New     string `json:"new"`
}

// DBHealth defines model for DBHealth.
type DBHealth struct {
	CanRunNow bool `json:"can_run_now"`
	Driver    struct {
		Label   *string            `json:"label,omitempty"`
		Pragmas *map[string]string `json:"pragmas,omitempty"`
	} `json:"driver"`
	Integrity struct {
		CheckedAt  *time.Time `json:"checked_at,omitempty"`
		DurationMs *int64     `json:"duration_ms,omitempty"`
		Status     string     `json:"status"`
	} `json:"integrity"`
	JournalMode     string  `json:"journal_mode"`
	LastManualRunAt *string `json:"last_manual_run_at,omitempty"`
	NextAvailableAt *string `json:"next_available_at,omitempty"`
	Running         bool    `json:"running"`
	Size            struct {
		FreelistBytes *int64 `json:"freelist_bytes,omitempty"`
		FreelistCount *int64 `json:"freelist_count,omitempty"`
		LogicalBytes  *int64 `json:"logical_bytes,omitempty"`
		OnDiskBytes   *int64 `json:"on_disk_bytes,omitempty"`
		PageCount     *int64 `json:"page_count,omitempty"`
		PageSize      *int64 `json:"page_size,omitempty"`
	} `json:"size"`
	Wal struct {
		Bytes         *int64 `json:"bytes,omitempty"`
		WarnOverBytes *int64 `json:"warn_over_bytes,omitempty"`
	} `json:"wal"`
}

// DashboardResponse defines model for DashboardResponse.
type DashboardResponse struct {
	RecentActivity      *[]AuditEvent           `json:"recent_activity,omitempty"`
	RepoCount           *int                    `json:"repo_count,omitempty"`
	ScanFindingsSummary *map[string]interface{} `json:"scan_findings_summary,omitempty"`
	StorageTotal        *int64                  `json:"storage_total,omitempty"`
	StorageUsed         *int64                  `json:"storage_used,omitempty"`
	UserCount           *int                    `json:"user_count,omitempty"`
}

// DockerPromoteRequest defines model for DockerPromoteRequest.
type DockerPromoteRequest struct {
	Digest     string  `json:"digest"`
	NewTag     *string `json:"new_tag,omitempty"`
	SourceRepo string  `json:"source_repo"`
}

// DockerPullExternalRequest defines model for DockerPullExternalRequest.
type DockerPullExternalRequest struct {
	CredId *int64  `json:"cred_id,omitempty"`
	Image  string  `json:"image"`
	Tag    *string `json:"tag,omitempty"`
}

// GCStatusResponse defines model for GCStatusResponse.
type GCStatusResponse struct {
	BytesFreed *int64                  `json:"bytes_freed,omitempty"`
	FinishedAt *time.Time              `json:"finished_at,omitempty"`
	JobId      *int64                  `json:"job_id,omitempty"`
	StartedAt  *time.Time              `json:"started_at,omitempty"`
	Status     *GCStatusResponseStatus `json:"status,omitempty"`
}

// GCStatusResponseStatus defines model for GCStatusResponse.Status.
type GCStatusResponseStatus string

// GCTriggerResponse defines model for GCTriggerResponse.
type GCTriggerResponse struct {
	JobId *int64 `json:"job_id,omitempty"`
}

// GitBlame defines model for GitBlame.
type GitBlame struct {
	Lines *[]struct {
		Author     *string    `json:"author,omitempty"`
		Content    *string    `json:"content,omitempty"`
		Date       *time.Time `json:"date,omitempty"`
		LineNumber *int       `json:"line_number,omitempty"`
		Sha        *string    `json:"sha,omitempty"`
	} `json:"lines,omitempty"`
	Path *string `json:"path,omitempty"`
}

// GitCommit defines model for GitCommit.
type GitCommit struct {
	AuthorDate     *time.Time `json:"author_date,omitempty"`
	AuthorEmail    *string    `json:"author_email,omitempty"`
	AuthorName     *string    `json:"author_name,omitempty"`
	CommitterDate  *time.Time `json:"committer_date,omitempty"`
	CommitterEmail *string    `json:"committer_email,omitempty"`
	CommitterName  *string    `json:"committer_name,omitempty"`
	Message        *string    `json:"message,omitempty"`
	ParentShas     *[]string  `json:"parent_shas,omitempty"`
	Sha            *string    `json:"sha,omitempty"`
}

// GitCompareResponse defines model for GitCompareResponse.
type GitCompareResponse struct {
	AheadBy  *int         `json:"ahead_by,omitempty"`
	Base     *string      `json:"base,omitempty"`
	BehindBy *int         `json:"behind_by,omitempty"`
	Commits  *[]GitCommit `json:"commits,omitempty"`
	Files    *[]struct {
		Patch  *string `json:"patch,omitempty"`
		Path   *string `json:"path,omitempty"`
		Status *string `json:"status,omitempty"`
	} `json:"files,omitempty"`
	Head *string `json:"head,omitempty"`
}

// GitDiff defines model for GitDiff.
type GitDiff struct {
	Files *[]struct {
		Patch  *string `json:"patch,omitempty"`
		Path   *string `json:"path,omitempty"`
		Status *string `json:"status,omitempty"`
	} `json:"files,omitempty"`
	Message *string `json:"message,omitempty"`
	Sha     *string `json:"sha,omitempty"`
	Stats   *struct {
		Additions    *int `json:"additions,omitempty"`
		Deletions    *int `json:"deletions,omitempty"`
		FilesChanged *int `json:"files_changed,omitempty"`
	} `json:"stats,omitempty"`
}

// GitFileContent defines model for GitFileContent.
type GitFileContent struct {
	Content  *string `json:"content,omitempty"`
	Encoding *string `json:"encoding,omitempty"`
	Name     *string `json:"name,omitempty"`
	Path     *string `json:"path,omitempty"`
	Sha      *string `json:"sha,omitempty"`
	Size     *int64  `json:"size,omitempty"`
}

// GitRef defines model for GitRef.
type GitRef struct {
	Name *string     `json:"name,omitempty"`
	Sha  *string     `json:"sha,omitempty"`
	Type *GitRefType `json:"type,omitempty"`
}

// GitRefType defines model for GitRef.Type.
type GitRefType string

// GitTreeEntry defines model for GitTreeEntry.
type GitTreeEntry struct {
	Name *string           `json:"name,omitempty"`
	Path *string           `json:"path,omitempty"`
	Sha  *string           `json:"sha,omitempty"`
	Size *int64            `json:"size,omitempty"`
	Type *GitTreeEntryType `json:"type,omitempty"`
}

// GitTreeEntryType defines model for GitTreeEntry.Type.
type GitTreeEntryType string

// JobsSummary defines model for JobsSummary.
type JobsSummary struct {
	FailedLast24h   int        `json:"failed_last_24h"`
	LastCompletedAt *time.Time `json:"last_completed_at"`
	LastFailedAt    *time.Time `json:"last_failed_at"`
	Queued          int        `json:"queued"`
	Running         int        `json:"running"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	IsSuperAdmin       bool   `json:"is_super_admin"`
	Login              string `json:"login"`
	MustChangePassword bool   `json:"must_change_password"`
}

// MaintenanceStatus defines model for MaintenanceStatus.
type MaintenanceStatus struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// MaintenanceToggle defines model for MaintenanceToggle.
type MaintenanceToggle struct {
	Enabled bool `json:"enabled"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	AvatarSeed         *string           `json:"avatar_seed,omitempty"`
	Email              string            `json:"email"`
	Id                 int64             `json:"id"`
	IsSuperAdmin       bool              `json:"is_super_admin"`
	Login              string            `json:"login"`
	MustChangePassword bool              `json:"must_change_password"`
	// ProjectRoles maps project name → caller's role ("maintainer" or
	// "viewer"). Omitted for super-admin callers (they bypass via
	// IsSuperAdmin) and for unauthenticated callers. Populated by
	// handleMe via MembersRepo.ListProjectRolesByNameForUser (D-16).
	ProjectRoles       map[string]string `json:"project_roles,omitempty"`
}

// MeUpdateRequest defines model for MeUpdateRequest.
type MeUpdateRequest struct {
	AvatarSeed *string `json:"avatar_seed,omitempty"`
	Email      *string `json:"email,omitempty"`
}

// MemberAction defines model for MemberAction.
type MemberAction struct {
	Status *string `json:"status,omitempty"`
}

// PaginatedList defines model for PaginatedList.
type PaginatedList struct {
	Items      *[]interface{} `json:"items,omitempty"`
	NextCursor *string        `json:"next_cursor,omitempty"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	DescriptionMd *string    `json:"description_md,omitempty"`
	Id            *int64     `json:"id,omitempty"`
	Name          *string    `json:"name,omitempty"`
}

// ProjectCreate defines model for ProjectCreate.
type ProjectCreate struct {
	DescriptionMd *string `json:"description_md,omitempty"`
	Name          string  `json:"name"`
}

// ProjectCreateResponse defines model for ProjectCreateResponse.
type ProjectCreateResponse struct {
	Id   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Repo defines model for Repo.
type Repo struct {
	AutoScan        *bool                `json:"auto_scan,omitempty"`
	BlockOnSeverity *RepoBlockOnSeverity `json:"block_on_severity,omitempty"`
	CreatedAt       *time.Time           `json:"created_at,omitempty"`
	DescriptionMd   *string              `json:"description_md,omitempty"`
	Id              *int64               `json:"id,omitempty"`
	Name            *string              `json:"name,omitempty"`
	ProjectId       *int64               `json:"project_id,omitempty"`
	PublicRead      *bool                `json:"public_read,omitempty"`
	SizeBytes       *int64               `json:"size_bytes,omitempty"`
	Type            *string              `json:"type,omitempty"`
}

// RepoBlockOnSeverity defines model for Repo.BlockOnSeverity.
type RepoBlockOnSeverity string

// RepoCreate defines model for RepoCreate.
type RepoCreate struct {
	AutoScan        *bool                      `json:"auto_scan,omitempty"`
	BlockOnSeverity *RepoCreateBlockOnSeverity `json:"block_on_severity,omitempty"`
	DescriptionMd   *string                    `json:"description_md,omitempty"`
	Name            string                     `json:"name"`
	PublicRead      *bool                      `json:"public_read,omitempty"`
	Type            string                     `json:"type"`
}

// RepoCreateBlockOnSeverity defines model for RepoCreate.BlockOnSeverity.
type RepoCreateBlockOnSeverity string

// RepoPatch defines model for RepoPatch.
type RepoPatch struct {
	AutoScan        *bool                     `json:"auto_scan,omitempty"`
	BlockOnSeverity *RepoPatchBlockOnSeverity `json:"block_on_severity,omitempty"`
	DescriptionMd   *string                   `json:"description_md,omitempty"`
	PublicRead      *bool                     `json:"public_read,omitempty"`
}

// RepoPatchBlockOnSeverity defines model for RepoPatch.BlockOnSeverity.
type RepoPatchBlockOnSeverity string

// S3Key defines model for S3Key.
type S3Key struct {
	AccessKeyId *string    `json:"access_key_id,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Label       *string    `json:"label,omitempty"`
	LastUsedAt  *time.Time `json:"last_used_at,omitempty"`
}

// S3KeyCreate defines model for S3KeyCreate.
type S3KeyCreate struct {
	Label string `json:"label"`
}

// S3KeyCreateResponse defines model for S3KeyCreateResponse.
type S3KeyCreateResponse struct {
	AccessKeyId *string    `json:"access_key_id,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Label       *string    `json:"label,omitempty"`

	// Secret Shown once at creation time only
	Secret *string `json:"secret,omitempty"`
}

// SBOMRef defines model for SBOMRef.
type SBOMRef struct {
	DownloadUrl *string `json:"download_url,omitempty"`
	Format      *string `json:"format,omitempty"`
	ScanId      *int64  `json:"scan_id,omitempty"`
}

// Scan defines model for Scan.
type Scan struct {
	ArtifactId          *string     `json:"artifact_id,omitempty"`
	ArtifactKind        *string     `json:"artifact_kind,omitempty"`
	Attempts            *int64      `json:"attempts,omitempty"`
	CreatedAt           *time.Time  `json:"created_at,omitempty"`
	FinishedAt          *time.Time  `json:"finished_at,omitempty"`
	Id                  *int64      `json:"id,omitempty"`
	LastError           *string     `json:"last_error,omitempty"`
	RepoId              *int64      `json:"repo_id,omitempty"`
	SbomPath            *string     `json:"sbom_path,omitempty"`
	SeveritySummaryJson *string     `json:"severity_summary_json,omitempty"`
	StartedAt           *time.Time  `json:"started_at,omitempty"`
	Status              *ScanStatus `json:"status,omitempty"`
	TrivyDbVersion      *string     `json:"trivy_db_version,omitempty"`
}

// ScanStatus defines model for Scan.Status.
type ScanStatus string

// ScanRow defines model for ScanRow.
type ScanRow struct {
	ArtifactId          string     `json:"artifact_id"`
	ArtifactKind        string     `json:"artifact_kind"`
	Attempts            int64      `json:"attempts"`
	CreatedAt           time.Time  `json:"created_at"`
	FinishedAt          *time.Time `json:"finished_at,omitempty"`
	Id                  int64      `json:"id"`
	LastError           *string    `json:"last_error,omitempty"`
	RepoId              int64      `json:"repo_id"`
	SbomPath            *string    `json:"sbom_path,omitempty"`
	SeveritySummaryJson *string    `json:"severity_summary_json,omitempty"`
	StartedAt           *time.Time `json:"started_at,omitempty"`
	Status              string     `json:"status"`
	TrivyDbVersion      *string    `json:"trivy_db_version,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Items      *[]SearchResult `json:"items,omitempty"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	EntityId *int64            `json:"entity_id,omitempty"`
	Kind     *SearchResultKind `json:"kind,omitempty"`
	Location *string           `json:"location,omitempty"`
	Name     *string           `json:"name,omitempty"`
	Score    *float64          `json:"score,omitempty"`
	Severity *string           `json:"severity,omitempty"`
}

// SearchResultKind defines model for SearchResult.Kind.
type SearchResultKind string

// SettingsMap defines model for SettingsMap.
type SettingsMap map[string]string

// SettingsPatch defines model for SettingsPatch.
type SettingsPatch map[string]string

// SetupStatusResponse defines model for SetupStatusResponse.
type SetupStatusResponse struct {
	// NeedsSetup true while the users table has zero live rows. Flips to false permanently after the first successful POST /setup/superadmin.
	NeedsSetup bool `json:"needs_setup"`
}

// SetupSuperAdminBody defines model for SetupSuperAdminBody.
type SetupSuperAdminBody struct {
	Email    string `json:"email"`
	Login    string `json:"login"`
	Password string `json:"password"`
}

// SetupSuperAdminReply defines model for SetupSuperAdminReply.
type SetupSuperAdminReply struct {
	IsSuperAdmin bool   `json:"is_super_admin"`
	Login        string `json:"login"`
}

// StatusOK defines model for StatusOK.
type StatusOK struct {
	Status *string `json:"status,omitempty"`
}

// SyncJob defines model for SyncJob.
type SyncJob struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// CurrentStep Human-readable current step, e.g. 'layer 3 of 7' (OCI), 'pulling redis_7.2.0' (APT), or 'chart 2 of 12 · redis-17.0.0.tgz' (Helm). Empty when not yet started.
	CurrentStep *string `json:"current_step,omitempty"`
	Error       *string `json:"error,omitempty"`

	// FilesSynced Count of files newly added during sync. Written once at sync completion by each protocol handler (not the throttled progress path). 0 for running jobs and legacy rows.
	FilesSynced *int64     `json:"files_synced,omitempty"`
	FinishedAt  *time.Time `json:"finished_at,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Kind        *string    `json:"kind,omitempty"`
	Log         *string    `json:"log,omitempty"`

	// ProgressBytes Bytes downloaded so far for the running sync. Always 0 for Helm (step-based progress — D-11).
	ProgressBytes *int64         `json:"progress_bytes,omitempty"`
	RepoId        *int64         `json:"repo_id,omitempty"`
	StartedAt     *time.Time     `json:"started_at,omitempty"`
	Status        *SyncJobStatus `json:"status,omitempty"`

	// TotalBytes Total bytes expected for the sync. Always 0 for Helm and when the upstream doesn't report sizes (D-11).
	TotalBytes *int64 `json:"total_bytes,omitempty"`
}

// SyncJobStatus defines model for SyncJob.Status.
type SyncJobStatus string

// SyncRequest defines model for SyncRequest.
type SyncRequest struct {
	CredId    *int64 `json:"cred_id,omitempty"`
	SourceUrl string `json:"source_url"`
}

// TLSCertInfo defines model for TLSCertInfo.
type TLSCertInfo struct {
	FingerprintSha256 *string            `json:"fingerprint_sha256,omitempty"`
	Issuer            *string            `json:"issuer,omitempty"`
	NotAfter          *time.Time         `json:"not_after,omitempty"`
	NotBefore         *time.Time         `json:"not_before,omitempty"`
	Serial            *string            `json:"serial,omitempty"`
	Source            *TLSCertInfoSource `json:"source,omitempty"`
	Subject           *string            `json:"subject,omitempty"`
}

// TLSCertInfoSource defines model for TLSCertInfo.Source.
type TLSCertInfoSource string

// TLSHistoryEntry defines model for TLSHistoryEntry.
type TLSHistoryEntry struct {
	FingerprintSha256 *string    `json:"fingerprint_sha256,omitempty"`
	Subject           *string    `json:"subject,omitempty"`
	UploadedAt        *time.Time `json:"uploaded_at,omitempty"`
	UploadedBy        *string    `json:"uploaded_by,omitempty"`
}

// TrashEntry defines model for TrashEntry.
type TrashEntry struct {
	DeletedAt          *time.Time `json:"deleted_at,omitempty"`
	DeletedBy          *string    `json:"deleted_by,omitempty"`
	Id                 *string    `json:"id,omitempty"`
	Name               *string    `json:"name,omitempty"`
	OriginalLocation   *string    `json:"original_location,omitempty"`
	RetentionCountdown *string    `json:"retention_countdown,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// TrashListResponse defines model for TrashListResponse.
type TrashListResponse struct {
	Items      *[]TrashEntry `json:"items,omitempty"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

// TrivyDBStatus defines model for TrivyDBStatus.
type TrivyDBStatus struct {
	AgeHours  *float64             `json:"age_hours,omitempty"`
	AppliedAt *time.Time           `json:"applied_at,omitempty"`
	Source    *TrivyDBStatusSource `json:"source,omitempty"`
	Stale     *bool                `json:"stale,omitempty"`
	Version   *string              `json:"version,omitempty"`
}

// TrivyDBStatusSource defines model for TrivyDBStatus.Source.
type TrivyDBStatusSource string

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	ArtifactCount *int   `json:"artifact_count,omitempty"`
	ScanId        *int64 `json:"scan_id,omitempty"`
}

// UpstreamCred defines model for UpstreamCred.
type UpstreamCred struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Host      *string    `json:"host,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Kind      *string    `json:"kind,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Username  *string    `json:"username,omitempty"`
}

// UpstreamCredCreate defines model for UpstreamCredCreate.
type UpstreamCredCreate struct {
	Host     string  `json:"host"`
	Kind     string  `json:"kind"`
	Password *string `json:"password,omitempty"`
	Token    *string `json:"token,omitempty"`
	Username *string `json:"username,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarSeed         *string    `json:"avatar_seed,omitempty"`
	CreatedAt          *time.Time `json:"created_at,omitempty"`
	Email              *string    `json:"email,omitempty"`
	Id                 *int64     `json:"id,omitempty"`
	IsSuperAdmin       *bool      `json:"is_super_admin,omitempty"`
	Login              *string    `json:"login,omitempty"`
	MustChangePassword *bool      `json:"must_change_password,omitempty"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Email string `json:"email"`
	Login string `json:"login"`
}

// UserCreateResponse defines model for UserCreateResponse.
type UserCreateResponse struct {
	Login           string `json:"login"`
	OneTimePassword string `json:"one_time_password"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	Email        *string `json:"email,omitempty"`
	IsSuperAdmin *bool   `json:"is_super_admin,omitempty"`
}

// Vulnerability defines model for Vulnerability.
type Vulnerability struct {
	CveId          *string                `json:"cve_id,omitempty"`
	Description    *string                `json:"description,omitempty"`
	FixedVersion   *string                `json:"fixed_version,omitempty"`
	Id             *int64                 `json:"id,omitempty"`
	PackageName    *string                `json:"package_name,omitempty"`
	PackageVersion *string                `json:"package_version,omitempty"`
	ScanId         *int64                 `json:"scan_id,omitempty"`
	Severity       *VulnerabilitySeverity `json:"severity,omitempty"`
	Title          *string                `json:"title,omitempty"`
}

// VulnerabilitySeverity defines model for Vulnerability.Severity.
type VulnerabilitySeverity string

// VulnerabilityRow defines model for VulnerabilityRow.
type VulnerabilityRow struct {
	CveId          string  `json:"cve_id"`
	Description    *string `json:"description,omitempty"`
	FixedVersion   string  `json:"fixed_version"`
	Id             int64   `json:"id"`
	PackageName    string  `json:"package_name"`
	PackageVersion string  `json:"package_version"`
	ScanId         int64   `json:"scan_id"`
	Severity       string  `json:"severity"`
	Title          string  `json:"title"`
}

// WipeResponse defines model for WipeResponse.
type WipeResponse struct {
	ArtifactCount *int64  `json:"artifact_count,omitempty"`
	BytesFreed    *int64  `json:"bytes_freed,omitempty"`
	TrashId       *string `json:"trash_id,omitempty"`
}

// CursorParam defines model for cursorParam.
type CursorParam = string

// LimitParam defines model for limitParam.
type LimitParam = int

// NotFoundError defines model for NotFoundError.
type NotFoundError = ApiErrorEnvelope

// OperatorActionRequired defines model for OperatorActionRequired.
type OperatorActionRequired = ApiErrorEnvelope

// PermissionError defines model for PermissionError.
type PermissionError = ApiErrorEnvelope

// TransientError defines model for TransientError.
type TransientError = ApiErrorEnvelope

// ValidationError defines model for ValidationError.
type ValidationError = ApiErrorEnvelope

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	Actor      *string      `form:"actor,omitempty" json:"actor,omitempty"`
	Action     *string      `form:"action,omitempty" json:"action,omitempty"`
	TargetKind *string      `form:"target_kind,omitempty" json:"target_kind,omitempty"`
	From       *time.Time   `form:"from,omitempty" json:"from,omitempty"`
	To         *time.Time   `form:"to,omitempty" json:"to,omitempty"`
	Outcome    *string      `form:"outcome,omitempty" json:"outcome,omitempty"`
	Limit      *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor     *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UploadTLSCertMultipartBody defines parameters for UploadTLSCert.
type UploadTLSCertMultipartBody struct {
	Cert *openapi_types.File `json:"cert,omitempty"`
	Key  *openapi_types.File `json:"key,omitempty"`
}

// ListTrashParams defines parameters for ListTrash.
type ListTrashParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UploadTrivyDBMultipartBody defines parameters for UploadTrivyDB.
type UploadTrivyDBMultipartBody struct {
	Db *openapi_types.File `json:"db,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetProjectActivityParams defines parameters for GetProjectActivity.
type GetProjectActivityParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListReposParams defines parameters for ListRepos.
type ListReposParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GitCommitsParams defines parameters for GitCommits.
type GitCommitsParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListScansParams defines parameters for ListScans.
type ListScansParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListSyncJobsParams defines parameters for ListSyncJobs.
type ListSyncJobsParams struct {
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UploadArtifactMultipartBody defines parameters for UploadArtifact.
type UploadArtifactMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q        string            `form:"q" json:"q"`
	Kind     *SearchParamsKind `form:"kind,omitempty" json:"kind,omitempty"`
	Severity *string           `form:"severity,omitempty" json:"severity,omitempty"`
	Project  *string           `form:"project,omitempty" json:"project,omitempty"`
	Limit    *LimitParam       `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor   *CursorParam      `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SearchParamsKind defines parameters for Search.
type SearchParamsKind string

// ToggleMaintenanceJSONRequestBody defines body for ToggleMaintenance for application/json ContentType.
type ToggleMaintenanceJSONRequestBody = MaintenanceToggle

// PatchSettingsJSONRequestBody defines body for PatchSettings for application/json ContentType.
type PatchSettingsJSONRequestBody = SettingsPatch

// UploadTLSCertMultipartRequestBody defines body for UploadTLSCert for multipart/form-data ContentType.
type UploadTLSCertMultipartRequestBody UploadTLSCertMultipartBody

// UploadTrivyDBMultipartRequestBody defines body for UploadTrivyDB for multipart/form-data ContentType.
type UploadTrivyDBMultipartRequestBody UploadTrivyDBMultipartBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreate

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdate

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = MeUpdateRequest

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = APIKeyCreate

// CreateMyS3KeyJSONRequestBody defines body for CreateMyS3Key for application/json ContentType.
type CreateMyS3KeyJSONRequestBody = S3KeyCreate

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectCreate

// CreateProjectAPIKeyJSONRequestBody defines body for CreateProjectAPIKey for application/json ContentType.
type CreateProjectAPIKeyJSONRequestBody = APIKeyCreate

// CreateRepoJSONRequestBody defines body for CreateRepo for application/json ContentType.
type CreateRepoJSONRequestBody = RepoCreate

// DockerPromoteJSONRequestBody defines body for DockerPromote for application/json ContentType.
type DockerPromoteJSONRequestBody = DockerPromoteRequest

// DockerPullExternalJSONRequestBody defines body for DockerPullExternal for application/json ContentType.
type DockerPullExternalJSONRequestBody = DockerPullExternalRequest

// PatchRepoJSONRequestBody defines body for PatchRepo for application/json ContentType.
type PatchRepoJSONRequestBody = RepoPatch

// SyncRepoJSONRequestBody defines body for SyncRepo for application/json ContentType.
type SyncRepoJSONRequestBody = SyncRequest

// UploadArtifactMultipartRequestBody defines body for UploadArtifact for multipart/form-data ContentType.
type UploadArtifactMultipartRequestBody UploadArtifactMultipartBody

// CreateUpstreamCredJSONRequestBody defines body for CreateUpstreamCred for application/json ContentType.
type CreateUpstreamCredJSONRequestBody = UpstreamCredCreate

// CreateS3AccessKeyJSONRequestBody defines body for CreateS3AccessKey for application/json ContentType.
type CreateS3AccessKeyJSONRequestBody = S3KeyCreate

// SetupSuperAdminJSONRequestBody defines body for SetupSuperAdmin for application/json ContentType.
type SetupSuperAdminJSONRequestBody = SetupSuperAdminBody

// Getter for additional properties for ApiErrorEnvelope_Details. Returns the specified
// element and whether it was found
func (a ApiErrorEnvelope_Details) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ApiErrorEnvelope_Details
func (a *ApiErrorEnvelope_Details) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ApiErrorEnvelope_Details to handle AdditionalProperties
func (a *ApiErrorEnvelope_Details) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["fields"]; found {
		err = json.Unmarshal(raw, &a.Fields)
		if err != nil {
			return fmt.Errorf("error reading 'fields': %w", err)
		}
		delete(object, "fields")
	}

	if raw, found := object["operator_label"]; found {
		err = json.Unmarshal(raw, &a.OperatorLabel)
		if err != nil {
			return fmt.Errorf("error reading 'operator_label': %w", err)
		}
		delete(object, "operator_label")
	}

	if raw, found := object["operator_route"]; found {
		err = json.Unmarshal(raw, &a.OperatorRoute)
		if err != nil {
			return fmt.Errorf("error reading 'operator_route': %w", err)
		}
		delete(object, "operator_route")
	}

	if raw, found := object["retry_after_ms"]; found {
		err = json.Unmarshal(raw, &a.RetryAfterMs)
		if err != nil {
			return fmt.Errorf("error reading 'retry_after_ms': %w", err)
		}
		delete(object, "retry_after_ms")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ApiErrorEnvelope_Details to handle AdditionalProperties
func (a ApiErrorEnvelope_Details) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Field != nil {
		object["field"], err = json.Marshal(a.Field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field': %w", err)
		}
	}

	if a.Fields != nil {
		object["fields"], err = json.Marshal(a.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fields': %w", err)
		}
	}

	if a.OperatorLabel != nil {
		object["operator_label"], err = json.Marshal(a.OperatorLabel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'operator_label': %w", err)
		}
	}

	if a.OperatorRoute != nil {
		object["operator_route"], err = json.Marshal(a.OperatorRoute)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'operator_route': %w", err)
		}
	}

	if a.RetryAfterMs != nil {
		object["retry_after_ms"], err = json.Marshal(a.RetryAfterMs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'retry_after_ms': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
